# Generated by Django 5.1.1 on 2024-09-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mestredeobra',
            name='gerente_de_obra',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='mestre_de_obra',
        ),
        migrations.RemoveField(
            model_name='acompanhamento',
            name='mestre_de_obra',
        ),
        migrations.DeleteModel(
            name='GerenteDeObra',
        ),
        migrations.DeleteModel(
            name='MestreDeObra',
        ),
    ]
